language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - sudo apt-get update
  - sudo apt-get install libsctp1 libsctp-dev lksctp-tools
